# For this to work you need to have installed the vagrant-vmware-desktop plugin
# To install it just run "vagrant plugin install vagrant-vmware-desktop"

Vagrant.configure('2') do |config|
config.vm.provider "vmware_fusion"

config.vm.define "host1" do |host1|
  host1.vm.box = "rethinc-oss/ubuntu-2204"
  host1.vm.box_version = "20220819"
  host1.vm.hostname = "host1"
end
  
config.vm.define "host2" do |host2|
  host2.vm.box = "rethinc-oss/ubuntu-2204"
  host2.vm.box_version = "20220819"
  host2.vm.hostname = "host2"
  end
end