# For this to work you need to have installed the vagrant-vmware-desktop plugin
# To install it just run "vagrant plugin install vagrant-vmware-desktop"

Vagrant.configure('2') do |config|
vm.provider "vmware_fusion"
vm.memory = "768"
vm.cpus = "1"

vm.define "host1" do |host1|
  host1.vm.box = "debian/bullseye64"
  host1.vm.hostname = "host1"
  host1.vm.network :private_network, :ip => '192.168.56.100'
end
  
config.vm.define "host2" do |host2|
  host2.vm.box = "debian/bullseye64"
  host2.vm.hostname = "host2"
  host2.vm.network :private_network, :ip => '192.168.56.101'
  end
end