Vagrant.configure('2') do |config|
config.vm.provider "virtualbox" do |vb|
vb.memory = "768"
vb.cpus = "1"
end

config.vm.define "host1" do |host1|
  host1.vm.box = "debian/bullseye64"
  host1.vm.hostname = "host1"
  host1.vm.network :private_network, :ip => '192.168.56.100'
end
  
config.vm.define "host2" do |host2|
  host2.vm.box = "debian/bullseye64"
  host2.vm.hostname = "host2"
  host2.vm.network :private_network, :ip => '192.168.56.101'
  end
end